// <auto-generated />
using System;
using DotNetMath3.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetMath3.API.Migrations
{
    [DbContext(typeof(MathDataContext))]
    [Migration("20230622203947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DotNetMath3.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameEn")
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentCategoryCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DotNetMath3.API.Models.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MarkdownContentEn")
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentCategoryCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEn")
                        .HasColumnType("longtext");

                    b.HasKey("PageId");

                    b.HasIndex("ParentCategoryCategoryId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("DotNetMath3.API.Models.Category", b =>
                {
                    b.HasOne("DotNetMath3.API.Models.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DotNetMath3.API.Models.Page", b =>
                {
                    b.HasOne("DotNetMath3.API.Models.Category", "ParentCategory")
                        .WithMany("Pages")
                        .HasForeignKey("ParentCategoryCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DotNetMath3.API.Models.Category", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
